//
//  CrashReportScanner.swift
//  DynamicNotch
//
//  Scans ~/Library/Logs/DiagnosticReports for crash reports belonging to this
//  app's three processes - the main app, the XPC helper, and the separately-
//  installed thermal daemon. Covering all three matters: a helper/daemon crash
//  leaves the main app running, so the user would otherwise just see a feature
//  silently stop working with no explanation.
//
//  Dedup is filename-based (Defaults[.acknowledgedCrashReportFilenames]), not a
//  timestamp cutoff, so a crash that's been shown once never resurfaces even if
//  it's dismissed without being "fixed."
//

import Defaults
import Foundation

struct CrashReport: Identifiable, Equatable {
    let id: String  // the .ips filename
    let url: URL
    let process: String
    let date: Date
}

enum CrashReportScanner {
    /// The thermal daemon isn't a normal Xcode target - it's compiled by
    /// install-thermal-daemon.sh from an embedded source string and installed as
    /// /Library/BoringNotch/BoringNotchThermalDaemon, so its crash reports use that
    /// executable name, not anything tied to this app's bundle identifiers.
    private static let watchedPrefixes = [
        "DynamicNotch-", "DynamicNotchXPCHelper-", "BoringNotchThermalDaemon-",
    ]

    private static let diagnosticReportsDir: URL = {
        FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Logs/DiagnosticReports", isDirectory: true)
    }()

    /// Crash reports for our processes, newest first. `includeAcknowledged: true` is for
    /// the manual "Check for Crash Reports" row in Settings, which should still find a
    /// crash even if its auto-prompt was already dismissed; the default (false) is for
    /// the post-launch auto-prompt, which must never show the same crash twice.
    static func findNewCrashReports(includeAcknowledged: Bool = false) -> [CrashReport] {
        guard let files = try? FileManager.default.contentsOfDirectory(
            at: diagnosticReportsDir, includingPropertiesForKeys: [.contentModificationDateKey]
        ) else {
            AppLogger.general.debug("CrashReportScanner: could not list DiagnosticReports directory")
            return []
        }

        let acknowledged = Defaults[.acknowledgedCrashReportFilenames]

        return files.compactMap { url -> CrashReport? in
            let name = url.lastPathComponent
            guard name.hasSuffix(".ips") else { return nil }
            guard let prefix = watchedPrefixes.first(where: { name.hasPrefix($0) }) else { return nil }
            guard includeAcknowledged || !acknowledged.contains(name) else { return nil }

            guard let attributes = try? FileManager.default.attributesOfItem(atPath: url.path),
                  let modDate = attributes[.modificationDate] as? Date else { return nil }

            let process = String(prefix.dropLast())  // drop the trailing "-"
            return CrashReport(id: name, url: url, process: process, date: modDate)
        }.sorted { $0.date > $1.date }
    }

    /// Marks a crash report as shown, so it's never surfaced again - whether the user
    /// dismissed it or acted on it. "Check for Crash Reports" in Settings bypasses this
    /// by reading findNewCrashReports() directly only when explicitly asked.
    static func acknowledge(_ report: CrashReport) {
        var acknowledged = Defaults[.acknowledgedCrashReportFilenames]
        acknowledged.insert(report.id)
        Defaults[.acknowledgedCrashReportFilenames] = acknowledged
    }

    #if DEBUG
    /// Writes a fake-but-plausible .ips file into the real DiagnosticReports folder, so
    /// the menu bar's "Simulate Crash" can exercise the whole scanner/sheet/GitHub flow
    /// without actually terminating the app - unlike a real fatalError(), this can be
    /// run over and over without relaunching between tries.
    static func simulateCrash() {
        let timestamp = ISO8601DateFormatter().string(from: Date()).replacingOccurrences(of: ":", with: "-")
        let filename = "DynamicNotch-SIMULATED-\(timestamp).ips"
        let url = diagnosticReportsDir.appendingPathComponent(filename)

        let fakeReport = """
        *** SIMULATED CRASH — NOT A REAL CRASH ***
        This file was generated by DynamicNotch's menu bar "Simulate Crash" (Debug builds
        only), to test the crash-report flow without actually terminating the app.

        Process:    DynamicNotch [simulated]
        Date/Time:  \(Date())
        OS Version: \(ProcessInfo.processInfo.operatingSystemVersionString)

        Thread 0 Crashed (simulated):
        0   DynamicNotch    0x0000000000000000 CrashReportScanner.simulateCrash() + 0
        """

        do {
            try FileManager.default.createDirectory(at: diagnosticReportsDir, withIntermediateDirectories: true)
            try fakeReport.write(to: url, atomically: true, encoding: .utf8)
            AppLogger.general.notice("CrashReportScanner: wrote simulated crash report \(filename)")
        } catch {
            AppLogger.general.error("CrashReportScanner: failed to write simulated crash report, \(type(of: error))")
        }
    }
    #endif
}
